sudo: false
dist: trusty
language: python
python:
    - "2.7"
    - "3.6"
install:
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
    - pip install coveralls
script:
    - make coverage
    - sonar-scanner -Dsonar.login=$SONAR_TOKEN
after_success:
    - coveralls
addons:
    sonarcloud:
        organization: ictu-gros
